## YAML Template.
#---
#server:
#  port: 8080
#spring:
#  kafka:
#    bootstrap-servers: "172.17.0.2:9092"
#    
#---

#spring:
#  profiles: local
server:
  port: 8081
spring:
  kafka:
    bootstrap-servers: "localhost:9092" 

    
